In [0]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [0]:
!pip install pandasql

In [0]:
%load_ext sql
%config SqlMagic.autocommit=False # for engines that do not support autommit

In [0]:
import sqlite3

In [0]:
import pandasql as ps


In [0]:
import descartes
import geopandas as gpd
from shapely.geometry import point , polygon

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


In [0]:
from sklearn.model_selection import GridSearchCV, train_test_split
from xgboost import XGBRegressor

from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

from sklearn.metrics import accuracy_score


In [0]:
import xgboost
import csv as csv
from xgboost import plot_importance
from matplotlib import pyplot
from sklearn.model_selection import cross_val_score,KFold
from sklearn.metrics import mean_absolute_error
import matplotlib.pyplot as plt
from scipy.stats import skew
from collections import OrderedDict

In [0]:
import keras
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasRegressor

Using TensorFlow backend.


In [0]:
from sklearn.preprocessing import LabelEncoder

In [0]:
from sklearn.model_selection import GridSearchCV, train_test_split
from xgboost import XGBRegressor

from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from sklearn.cluster import KMeans


In [0]:
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
import seaborn as sns
import matplotlib.pyplot as plt
from math import sqrt
%matplotlib inline

In [0]:
import math
from scipy import stats

In [0]:
train = pd.read_csv('/content/drive/My Drive/Dataset (1)/Train.csv')

In [0]:
test = pd.read_csv('/content/drive/My Drive/Dataset (1)/Test.csv')

In [0]:
train.head()

id    realtionship_status  ... money_back_guarantee netgain
0  19717  Married-spouse-absent  ...                   No   False
1  31593     Married-civ-spouse  ...                   No   False
2   5681               Divorced  ...                  Yes   False
3  15491              Separated  ...                   No   False
4  23587     Married-civ-spouse  ...                   No    True

[5 rows x 12 columns]

In [0]:
test.head()

id realtionship_status  ... expensive money_back_guarantee
0   1             Widowed  ...       Low                   No
1   4  Married-civ-spouse  ...      High                  Yes
2   5            Divorced  ...       Low                   No
3   9  Married-civ-spouse  ...       Low                   No
4  10  Married-civ-spouse  ...       Low                  Yes

[5 rows x 11 columns]

In [0]:
train['industry'].value_counts()

Pharma           10339
Auto              6801
Political         4014
Entertainment     2765
Other             1333
ClassAction        796
Name: industry, dtype: int64

In [0]:
for i in list(set(train.columns) - set(['id','ratings','average_runtime(minutes_per_week)'])) :
  print (i) 
  print(np.round(train[i].value_counts() /train[i].count() ,2))
  print('----------------------------')

money_back_guarantee
Yes    0.5
No     0.5
Name: money_back_guarantee, dtype: float64
----------------------------
airtime
Primetime    0.60
Morning      0.33
Daytime      0.07
Name: airtime, dtype: float64
----------------------------
realtionship_status
Married-civ-spouse       0.45
Never-married            0.33
Divorced                 0.14
Widowed                  0.03
Separated                0.03
Married-spouse-absent    0.01
Married-AF-spouse        0.00
Name: realtionship_status, dtype: float64
----------------------------
genre
Comedy         0.85
Infomercial    0.10
Drama          0.03
Direct         0.01
Other          0.01
Name: genre, dtype: float64
----------------------------
airlocation
United-States                 0.89
Mexico                        0.02
International                 0.02
Philippines                   0.01
Germany                       0.00
Canada                        0.00
Cuba                          0.00
Puerto-Rico                   0.00
El-Salva

In [0]:
train.loc[:,['average_runtime(minutes_per_week)','ratings']].describe()

average_runtime(minutes_per_week)       ratings
count                       26048.000000  26048.000000
mean                           40.294111      0.038716
std                            12.479457      0.075852
min                             1.000000      0.000000
25%                            40.000000      0.027465
50%                            40.000000      0.027465
75%                            45.000000      0.027465
max                            99.000000      1.000000

In [0]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26048 entries, 0 to 26047
Data columns (total 12 columns):
id                                   26048 non-null int64
realtionship_status                  26048 non-null object
industry                             26048 non-null object
genre                                26048 non-null object
targeted_sex                         26048 non-null object
average_runtime(minutes_per_week)    26048 non-null int64
airtime                              26048 non-null object
airlocation                          26048 non-null object
ratings                              26048 non-null float64
expensive                            26048 non-null object
money_back_guarantee                 26048 non-null object
netgain                              26048 non-null bool
dtypes: bool(1), float64(1), int64(2), object(8)
memory usage: 2.2+ MB


In [0]:
train_1=pd.get_dummies(train , columns=['realtionship_status','industry','genre','targeted_sex','airtime','expensive','money_back_guarantee'])

In [0]:
train_1['loc_us']=np.where(train_1['airlocation']=='United-States',1,0)

In [0]:
train_1.head()

id  average_runtime(minutes_per_week)  ... money_back_guarantee_Yes  loc_us
0  19717                                 45  ...                        0       1
1  31593                                 45  ...                        0       1
2   5681                                 45  ...                        1       1
3  15491                                 40  ...                        0       1
4  23587                                 48  ...                        0       1

[5 rows x 34 columns]

In [0]:
train_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26048 entries, 0 to 26047
Data columns (total 34 columns):
id                                           26048 non-null int64
average_runtime(minutes_per_week)            26048 non-null int64
airlocation                                  26048 non-null object
ratings                                      26048 non-null float64
netgain                                      26048 non-null bool
realtionship_status_Divorced                 26048 non-null uint8
realtionship_status_Married-AF-spouse        26048 non-null uint8
realtionship_status_Married-civ-spouse       26048 non-null uint8
realtionship_status_Married-spouse-absent    26048 non-null uint8
realtionship_status_Never-married            26048 non-null uint8
realtionship_status_Separated                26048 non-null uint8
realtionship_status_Widowed                  26048 non-null uint8
industry_Auto                                26048 non-null uint8
industry_ClassAction           

In [0]:
train_1.drop(columns=['airlocation'],inplace=True)

In [0]:
x_train=train_1.drop(columns=['netgain'])

In [0]:
y_train=np.where(train_1['netgain']==True , 1 ,0)

In [0]:
pd.Series(y_train).value_counts()

0    19853
1     6195
dtype: int64

In [0]:
# Organize our data for training
X = x_train
Y = y_train
X, X_Val, Y, Y_Val = train_test_split(X, Y , train_size =0.7 , shuffle=True)

In [0]:
import keras
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout

from keras.wrappers.scikit_learn import KerasRegressor



# Model
model = Sequential()
model.add(Dense(512, input_dim=32, activation='relu'))
model.add(Dense(256, activation='relu'))
model.add(Dense(128,  activation='relu'))
model.add(Dense(64,  activation='relu'))
model.add(Dense(16,  activation='relu'))
model.add(Dense(1,  activation='sigmoid'))
# Compile model
model.compile(loss='binary_crossentropy', optimizer='adam' , metrics=['accuracy'])


model.fit(np.array(X), np.array(Y), epochs=10, batch_size=10)






Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where



Epoch 1/10





18233/18233 [==============================] - 10s 523us/step - loss: 4.1642 - acc: 0.7412
Epoch 2/10
18233/18233 [==============================] - 9s 478us/step - loss: 4.9075 - acc: 0.6943
Epoch 3/10
18233/18233 [==============================] - 9s 481us/step - loss: 3.8498 - acc: 0.7611
Epoch 4/10
18233/18233 [==============================] - 9s 490us/step - loss: 3.8498 - acc: 0.7611
Epoch 5/10
18233/18233 [==============================] - 9s 491us/step - loss: 3.8498 - acc: 0.7611
Epoch 6/10
18233/18233 [==============================] - 9s 486us/step - loss: 3.8498 - acc: 0.7611
Epoch 7/10
18233/18233 [==============================] - 9s 477us/step - loss: 3.8498 - acc: 0.7611
Epoch 8/10
18233/18233 [==============================] - 9s 497us/step - loss: 3.8498 - acc: 0.7611
Epoch 9/10
18233/18233 [==============================] - 9s 482us/step - loss: 3.84

In [0]:
Y_Val

array([1, 1, 1, ..., 0, 0, 0])

In [0]:
pred_3 = model.predict(np.array(X_Val))


In [0]:
pred_3= pred_3.reshape(-1)

In [0]:
pd.Series(pred_3).value_counts()

0.000000    7813
0.000064       1
0.000404       1
dtype: int64

In [0]:
pred_3=np.where(pred_3>0,1,0)

In [0]:
pd.Series(pred_3).value_counts()

0    7813
1       2
dtype: int64

In [0]:
pred_3

array([0, 0, 0, ..., 0, 0, 0])

In [0]:
pd.Series(Y).value_counts()

0    13878
1     4355
dtype: int64

In [0]:

# Print the mse score
print(accuracy_score(Y_Val,pred_3)) 

0.7645553422904671


In [0]:
pd.Series(Y_Val).value_counts()

0    5975
1    1840
dtype: int64

In [0]:
pd.Series(pred_3.reshape(-1)).value_counts()

0    7813
1       2
dtype: int64

In [0]:
pd.Series(Y).value_counts()

0    13878
1     4355
dtype: int64

In [0]:
test_1=pd.get_dummies(test , columns=['realtionship_status','industry','genre','targeted_sex','airtime','expensive','money_back_guarantee'])

In [0]:
test_1['loc_us']=np.where(test_1['airlocation']=='United-States',1,0)

In [0]:
test_1.head()

id  average_runtime(minutes_per_week)  ... money_back_guarantee_Yes  loc_us
0   1                                 10  ...                        0       1
1   4                                 40  ...                        1       1
2   5                                 50  ...                        0       1
3   9                                 40  ...                        0       1
4  10                                 40  ...                        1       1

[5 rows x 33 columns]

In [0]:
test_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6513 entries, 0 to 6512
Data columns (total 33 columns):
id                                           6513 non-null int64
average_runtime(minutes_per_week)            6513 non-null int64
airlocation                                  6513 non-null object
ratings                                      6513 non-null float64
realtionship_status_Divorced                 6513 non-null uint8
realtionship_status_Married-AF-spouse        6513 non-null uint8
realtionship_status_Married-civ-spouse       6513 non-null uint8
realtionship_status_Married-spouse-absent    6513 non-null uint8
realtionship_status_Never-married            6513 non-null uint8
realtionship_status_Separated                6513 non-null uint8
realtionship_status_Widowed                  6513 non-null uint8
industry_Auto                                6513 non-null uint8
industry_ClassAction                         6513 non-null uint8
industry_Entertainment                       

In [0]:
test_1.drop(columns=['airlocation'],inplace=True)

In [0]:
x_test=test_1

In [0]:
pred_4 = model.predict(np.array(x_test))


In [0]:
pred_4=np.where(pred_4>0,1,0)

In [0]:
pred_4

array([[1],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [0]:
pred_4=pred_4.reshape(-1)

In [0]:
pd.Series(pred_4).value_counts()

0    6511
1       2
dtype: int64

In [0]:
pred_4 = np.where(pred_4 ==1 , True , False)

In [0]:
pd.DataFrame(pred_4 , index=test_1['id'],columns=['netgain']).to_csv('submission.csv')